#!/usr/bin/env python
#
# Created on Sat Apr 20 22:16:10 IST 2019
# Purpose :: Launcher for SeedCalculator
#
import sys
import math
#
version="1.0.0"
prog="SeedGerminator"


	
def opt_parser():
	if len(sys.argv) != 2 :
		usage()
	else:
		fname = sys.argv[1]
	return fname
		
def usage():
	print "Usage: SeedGerminator inputfile"
	print "\nVersion :: 1.0.0"
	print "Report bugs to <rajeshprasanth@rediffmail.com>"

def inpfilereader(filename):
	try:
    		ifile = open(filename, 'rb')
	except IOError:
    		print "Could not read file:", filename
    		sys.exit()

	with ifile:
    		for line in ifile:
    			if "maxseeds" in line:
				maxseeds = line.split(":")[1]
			if "model" in line:
				model = line.split(":")[1]
			if "AUC_lower_limit" in line:
				AUC_lower_limit = line.split(":")[1]
			if "AUC_upper_limit" in line:
				AUC_upper_limit = line.split(":")[1]
			if "fname_uniformity" in line:
				fname_uniformity = line.split(":")[1]
			if "fname_generic_t_calc" in line:
				fname_generic_t_calc = line.split(":")[1]
			if "fname_germination_data" in line:
				fname_germination_data = line.split(":")[1]
				
	return maxseeds,model,AUC_lower_limit,AUC_upper_limit,fname_uniformity,fname_generic_t_calc,fname_germination_data
    	

inp = opt_parser()
maxseeds,model,AUC_lower_limit,AUC_upper_limit,fname_uniformity,fname_generic_t_calc,fname_germination_data=inpfilereader(inp)

print "------------------------------------------"
print maxseeds,model,AUC_lower_limit,AUC_upper_limit,fname_uniformity,fname_generic_t_calc,fname_germination_data
print "------------------------------------------"
